# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rework_temp.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DataSamplingTools(object):
    def setupUi(self, DataSamplingTools):
        DataSamplingTools.setObjectName("DataSamplingTools")
        DataSamplingTools.resize(1250, 907)
        self.centralwidget = QtWidgets.QWidget(DataSamplingTools)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(60, 91))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.datasetButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetButton.sizePolicy().hasHeightForWidth())
        self.datasetButton.setSizePolicy(sizePolicy)
        self.datasetButton.setMinimumSize(QtCore.QSize(0, 0))
        self.datasetButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.datasetButton.setObjectName("datasetButton")
        self.horizontalLayout.addWidget(self.datasetButton)
        self.datasetLoadingTextLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetLoadingTextLabel.sizePolicy().hasHeightForWidth())
        self.datasetLoadingTextLabel.setSizePolicy(sizePolicy)
        self.datasetLoadingTextLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.datasetLoadingTextLabel.setMaximumSize(QtCore.QSize(50, 91))
        self.datasetLoadingTextLabel.setText("")
        self.datasetLoadingTextLabel.setObjectName("datasetLoadingTextLabel")
        self.horizontalLayout.addWidget(self.datasetLoadingTextLabel)
        self.datasetProgressBar = QtWidgets.QProgressBar(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetProgressBar.sizePolicy().hasHeightForWidth())
        self.datasetProgressBar.setSizePolicy(sizePolicy)
        self.datasetProgressBar.setMinimumSize(QtCore.QSize(100, 0))
        self.datasetProgressBar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.datasetProgressBar.setAcceptDrops(False)
        self.datasetProgressBar.setMaximum(336)
        self.datasetProgressBar.setProperty("value", 0)
        self.datasetProgressBar.setObjectName("datasetProgressBar")
        self.horizontalLayout.addWidget(self.datasetProgressBar)
        self.filePathLabel = QtWidgets.QLabel(self.groupBox)
        self.filePathLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filePathLabel.sizePolicy().hasHeightForWidth())
        self.filePathLabel.setSizePolicy(sizePolicy)
        self.filePathLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.filePathLabel.setMaximumSize(QtCore.QSize(47, 91))
        self.filePathLabel.setText("")
        self.filePathLabel.setObjectName("filePathLabel")
        self.horizontalLayout.addWidget(self.filePathLabel)
        self.datasetPickedLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetPickedLabel.sizePolicy().hasHeightForWidth())
        self.datasetPickedLabel.setSizePolicy(sizePolicy)
        self.datasetPickedLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.datasetPickedLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.datasetPickedLabel.setText("")
        self.datasetPickedLabel.setWordWrap(True)
        self.datasetPickedLabel.setObjectName("datasetPickedLabel")
        self.horizontalLayout.addWidget(self.datasetPickedLabel)
        self.datasetLoadingResultLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.datasetLoadingResultLabel.sizePolicy().hasHeightForWidth())
        self.datasetLoadingResultLabel.setSizePolicy(sizePolicy)
        self.datasetLoadingResultLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.datasetLoadingResultLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.datasetLoadingResultLabel.setText("")
        self.datasetLoadingResultLabel.setIndent(-1)
        self.datasetLoadingResultLabel.setObjectName("datasetLoadingResultLabel")
        self.horizontalLayout.addWidget(self.datasetLoadingResultLabel)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(169, 91))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.dataTableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.dataTableWidget.setObjectName("dataTableWidget")
        self.dataTableWidget.setColumnCount(0)
        self.dataTableWidget.setRowCount(0)
        self.verticalLayout_4.addWidget(self.dataTableWidget)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setMaximumSize(QtCore.QSize(169, 91))
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setMaximumSize(QtCore.QSize(169, 91))
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.totalNumberOfExamplesLabel = QtWidgets.QLabel(self.groupBox)
        self.totalNumberOfExamplesLabel.setMaximumSize(QtCore.QSize(169, 91))
        self.totalNumberOfExamplesLabel.setText("")
        self.totalNumberOfExamplesLabel.setObjectName("totalNumberOfExamplesLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.totalNumberOfExamplesLabel)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(13)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMaximumSize(QtCore.QSize(169, 91))
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.numberOfNegativeExamplesLabel = QtWidgets.QLabel(self.groupBox)
        self.numberOfNegativeExamplesLabel.setEnabled(True)
        self.numberOfNegativeExamplesLabel.setMaximumSize(QtCore.QSize(169, 81))
        self.numberOfNegativeExamplesLabel.setAutoFillBackground(False)
        self.numberOfNegativeExamplesLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.numberOfNegativeExamplesLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.numberOfNegativeExamplesLabel.setText("")
        self.numberOfNegativeExamplesLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.numberOfNegativeExamplesLabel.setObjectName("numberOfNegativeExamplesLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.numberOfNegativeExamplesLabel)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.imbalancedRatioLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imbalancedRatioLabel.sizePolicy().hasHeightForWidth())
        self.imbalancedRatioLabel.setSizePolicy(sizePolicy)
        self.imbalancedRatioLabel.setMaximumSize(QtCore.QSize(169, 16777215))
        self.imbalancedRatioLabel.setText("")
        self.imbalancedRatioLabel.setObjectName("imbalancedRatioLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.imbalancedRatioLabel)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.targetClassPercentageLabel = QtWidgets.QLabel(self.groupBox)
        self.targetClassPercentageLabel.setMaximumSize(QtCore.QSize(169, 16777215))
        self.targetClassPercentageLabel.setText("")
        self.targetClassPercentageLabel.setObjectName("targetClassPercentageLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.targetClassPercentageLabel)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setMaximumSize(QtCore.QSize(169, 91))
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setMaximumSize(QtCore.QSize(169, 91))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setMaximumSize(QtCore.QSize(169, 91))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(13)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMaximumSize(QtCore.QSize(169, 91))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMaximumSize(QtCore.QSize(169, 81))
        self.label_16.setAutoFillBackground(False)
        self.label_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_16)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(110, 91))
        self.label_3.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.resamplingAlgorithms = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resamplingAlgorithms.sizePolicy().hasHeightForWidth())
        self.resamplingAlgorithms.setSizePolicy(sizePolicy)
        self.resamplingAlgorithms.setMinimumSize(QtCore.QSize(150, 0))
        self.resamplingAlgorithms.setMaximumSize(QtCore.QSize(150, 16777215))
        self.resamplingAlgorithms.setObjectName("resamplingAlgorithms")
        self.horizontalLayout_6.addWidget(self.resamplingAlgorithms)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setMinimumSize(QtCore.QSize(50, 0))
        self.toolButton_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout_6.addWidget(self.toolButton_2)
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_37.sizePolicy().hasHeightForWidth())
        self.label_37.setSizePolicy(sizePolicy)
        self.label_37.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_6.addWidget(self.label_37)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_4.addWidget(self.label_32)
        self.outputDirectoryButton = QtWidgets.QPushButton(self.groupBox_2)
        self.outputDirectoryButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.outputDirectoryButton.setObjectName("outputDirectoryButton")
        self.horizontalLayout_4.addWidget(self.outputDirectoryButton)
        self.outputDirectoryPickedLabel = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputDirectoryPickedLabel.sizePolicy().hasHeightForWidth())
        self.outputDirectoryPickedLabel.setSizePolicy(sizePolicy)
        self.outputDirectoryPickedLabel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.outputDirectoryPickedLabel.setText("")
        self.outputDirectoryPickedLabel.setWordWrap(True)
        self.outputDirectoryPickedLabel.setObjectName("outputDirectoryPickedLabel")
        self.horizontalLayout_4.addWidget(self.outputDirectoryPickedLabel)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.startButton = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_5.addWidget(self.startButton)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.resampleProgressBar = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resampleProgressBar.sizePolicy().hasHeightForWidth())
        self.resampleProgressBar.setSizePolicy(sizePolicy)
        self.resampleProgressBar.setProperty("value", 0)
        self.resampleProgressBar.setObjectName("resampleProgressBar")
        self.horizontalLayout_5.addWidget(self.resampleProgressBar)
        self.samplingResultLabel = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.samplingResultLabel.sizePolicy().hasHeightForWidth())
        self.samplingResultLabel.setSizePolicy(sizePolicy)
        self.samplingResultLabel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.samplingResultLabel.setText("")
        self.samplingResultLabel.setObjectName("samplingResultLabel")
        self.horizontalLayout_5.addWidget(self.samplingResultLabel)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_36.sizePolicy().hasHeightForWidth())
        self.label_36.setSizePolicy(sizePolicy)
        self.label_36.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.verticalLayout_6.addWidget(self.label_36)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setMaximumSize(QtCore.QSize(169, 91))
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setMaximumSize(QtCore.QSize(169, 91))
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.totalNumberOfExamplesResampledLabel = QtWidgets.QLabel(self.groupBox_2)
        self.totalNumberOfExamplesResampledLabel.setMaximumSize(QtCore.QSize(169, 91))
        self.totalNumberOfExamplesResampledLabel.setText("")
        self.totalNumberOfExamplesResampledLabel.setObjectName("totalNumberOfExamplesResampledLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.totalNumberOfExamplesResampledLabel)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(13)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMaximumSize(QtCore.QSize(169, 91))
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.numberOfNegativeExamplesResampledLabel = QtWidgets.QLabel(self.groupBox_2)
        self.numberOfNegativeExamplesResampledLabel.setEnabled(True)
        self.numberOfNegativeExamplesResampledLabel.setMaximumSize(QtCore.QSize(169, 81))
        self.numberOfNegativeExamplesResampledLabel.setAutoFillBackground(False)
        self.numberOfNegativeExamplesResampledLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.numberOfNegativeExamplesResampledLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.numberOfNegativeExamplesResampledLabel.setText("")
        self.numberOfNegativeExamplesResampledLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.numberOfNegativeExamplesResampledLabel.setObjectName("numberOfNegativeExamplesResampledLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.numberOfNegativeExamplesResampledLabel)
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setObjectName("label_25")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.imbalancedRatioResampledLabel = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imbalancedRatioResampledLabel.sizePolicy().hasHeightForWidth())
        self.imbalancedRatioResampledLabel.setSizePolicy(sizePolicy)
        self.imbalancedRatioResampledLabel.setMaximumSize(QtCore.QSize(169, 16777215))
        self.imbalancedRatioResampledLabel.setText("")
        self.imbalancedRatioResampledLabel.setObjectName("imbalancedRatioResampledLabel")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.imbalancedRatioResampledLabel)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.targetClassPercentageResampledLabel = QtWidgets.QLabel(self.groupBox_2)
        self.targetClassPercentageResampledLabel.setMaximumSize(QtCore.QSize(169, 16777215))
        self.targetClassPercentageResampledLabel.setText("")
        self.targetClassPercentageResampledLabel.setObjectName("targetClassPercentageResampledLabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.targetClassPercentageResampledLabel)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setMaximumSize(QtCore.QSize(169, 91))
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setMaximumSize(QtCore.QSize(169, 91))
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_28)
        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(13)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMaximumSize(QtCore.QSize(169, 91))
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMaximumSize(QtCore.QSize(169, 81))
        self.label_30.setAutoFillBackground(False)
        self.label_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_30.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_30.setText("")
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_30)
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setMaximumSize(QtCore.QSize(169, 91))
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_4)
        self.horizontalLayout_3.addLayout(self.formLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        DataSamplingTools.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(DataSamplingTools)
        self.statusbar.setObjectName("statusbar")
        DataSamplingTools.setStatusBar(self.statusbar)

        self.retranslateUi(DataSamplingTools)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DataSamplingTools)

    def retranslateUi(self, DataSamplingTools):
        _translate = QtCore.QCoreApplication.translate
        DataSamplingTools.setWindowTitle(_translate("DataSamplingTools", "DataSamplingTools"))
        self.groupBox.setTitle(_translate("DataSamplingTools", "Original Data"))
        self.label_2.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_2.setText(_translate("DataSamplingTools", "Select a file:"))
        self.datasetButton.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.datasetButton.setText(_translate("DataSamplingTools", "..."))
        self.datasetLoadingTextLabel.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.filePathLabel.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.datasetLoadingResultLabel.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_4.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_4.setText(_translate("DataSamplingTools", "Table view"))
        self.label_8.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_8.setText(_translate("DataSamplingTools", "Basic Information"))
        self.label_9.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_9.setText(_translate("DataSamplingTools", "# Examples:"))
        self.totalNumberOfExamplesLabel.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_11.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_11.setText(_translate("DataSamplingTools", "# Negative examples:"))
        self.numberOfNegativeExamplesLabel.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_18.setText(_translate("DataSamplingTools", "Imbalanced ratio:"))
        self.label_7.setText(_translate("DataSamplingTools", "% Negative examples:"))
        self.label_17.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_17.setText(_translate("DataSamplingTools", "Graphics"))
        self.pushButton.setText(_translate("DataSamplingTools", "Standard"))
        self.pushButton_2.setText(_translate("DataSamplingTools", "PCA"))
        self.label_13.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_14.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_15.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_16.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.groupBox_2.setTitle(_translate("DataSamplingTools", "Resampled Data"))
        self.label_3.setText(_translate("DataSamplingTools", "Resampling Algorithm:"))
        self.toolButton_2.setText(_translate("DataSamplingTools", "Tune..."))
        self.label_32.setText(_translate("DataSamplingTools", "Output dir:"))
        self.outputDirectoryButton.setText(_translate("DataSamplingTools", "..."))
        self.startButton.setText(_translate("DataSamplingTools", "Start sampling..."))
        self.label_20.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_20.setText(_translate("DataSamplingTools", "Basic Information"))
        self.label_21.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_21.setText(_translate("DataSamplingTools", "#Examples:"))
        self.totalNumberOfExamplesResampledLabel.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_23.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_23.setText(_translate("DataSamplingTools", "#Negative Examples:"))
        self.numberOfNegativeExamplesResampledLabel.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_25.setText(_translate("DataSamplingTools", "Imbalanced ratio:"))
        self.label_10.setText(_translate("DataSamplingTools", "% Negative Examples:"))
        self.label_27.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_28.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_29.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_30.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_31.setToolTip(_translate("DataSamplingTools", "Only csv datasets are acceptable!"))
        self.label_31.setText(_translate("DataSamplingTools", "Graphics"))
        self.pushButton_3.setText(_translate("DataSamplingTools", "Standard"))
        self.pushButton_4.setText(_translate("DataSamplingTools", "PCA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("DataSamplingTools", "Data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("DataSamplingTools", "Classification"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("DataSamplingTools", "Classification Results"))
